In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
import time

In [5]:
# A= [0,1,2,3,....,100000000]
# B= [0,1,2,3,....,100000000]
# C= [0,2,6,.....,200000000]

In [6]:
#saf python ile kodlama
baslangic = time.time()
A = list(range(100000001))
B = list(range(100000001))
C = []
for i in range(len(B)):
    toplam = A[i] + B[i]
    C.append(toplam)
bitis = time.time()
sure = bitis - baslangic
print("Saf Python ile çalışma süresi: ", sure)

Saf Python ile çalışma süresi:  13.260147333145142


In [7]:
veriler = ['Ahmet','Ömer','Faruk','Doğan']
#            0    ,  1    ,  2   ,   3
print(veriler[0])

for veri in veriler:
  print(veri)

print('-'*5)
for i in range(len(veriler)):
  print(veriler[i])

Ahmet
Ahmet
Ömer
Faruk
Doğan
-----
Ahmet
Ömer
Faruk
Doğan


In [8]:
baslangic = time.time()
A = np.arange(10000001)
B = np.arange(10000001)
C = A + B
bitis = time.time()
sure = bitis-baslangic
print('Numpy çalışma süresi: ',sure)

Numpy çalışma süresi:  1.6063451766967773


In [9]:
numbers = [10,32,54,78,95]
arr1 = np.array(numbers)
print(arr1)
print(type(arr1))

[10 32 54 78 95]
<class 'numpy.ndarray'>


In [10]:
# arrange(bitis) arrange(baslangic, bitis) arange(baslangic, bitis, miktar)
ar1 = np.arange(2,25,2)
ar1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [11]:
# linspace(baslangic, bitis, miktar)
ar2 = np.linspace(10,34,8)
ar2

array([10.        , 13.42857143, 16.85714286, 20.28571429, 23.71428571,
       27.14285714, 30.57142857, 34.        ])

In [12]:
ar1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [14]:
a = ar1.astype(str)
a

array(['2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24'],
      dtype='<U21')

In [15]:
# 1 lerden oluşan diziler
# ones(adet)
birler = np.ones(6).astype(int)
birler

array([1, 1, 1, 1, 1, 1])

In [16]:
# zeros(adet) sıfırdan oluşan diziler oluşturmak için kullanılır
sifirlar = np.zeros(25).astype(int)
sifirlar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [17]:
# repeat(sayı, adet)
ar3 = np.repeat(25,6)
ar3

array([25, 25, 25, 25, 25, 25])

In [33]:
ar4 = np.repeat([10,20,30],3)
print(*ar4)

10 10 10 20 20 20 30 30 30


In [31]:
ar44 = np.tile([10,20,30],3)
ar44

array([10, 20, 30, 10, 20, 30, 10, 20, 30])

In [34]:
# random sayılar
a = np.random.randn(25)
a

array([-0.62159471, -0.02922024, -2.3516256 ,  0.28019169, -0.14443891,
        1.88186664, -0.69230424, -0.90615768,  0.46489746, -0.54837983,
        0.02429031,  0.26773847, -0.41328164,  1.6296367 , -1.7064222 ,
       -0.27121126,  1.4454462 , -0.98864889, -0.61462835,  0.58942594,
       -0.33537455, -0.5107198 ,  0.668352  ,  0.1313562 ,  0.54539332])

In [37]:
b = np.random.randint(123,654,150)
b

array([282, 641, 514, 603, 586, 573, 197, 390, 337, 583, 542, 416, 413,
       408, 450, 368, 440, 418, 398, 486, 609, 183, 524, 135, 380, 274,
       468, 364, 387, 342, 217, 404, 646, 514, 178, 237, 642, 357, 284,
       602, 212, 374, 302, 371, 536, 230, 618, 576, 187, 652, 130, 506,
       321, 559, 514, 537, 409, 346, 154, 494, 261, 565, 273, 392, 391,
       618, 319, 255, 302, 334, 292, 318, 615, 522, 494, 341, 373, 616,
       176, 164, 445, 311, 594, 462, 314, 282, 479, 438, 129, 581, 597,
       155, 150, 550, 368, 194, 352, 415, 508, 555, 431, 167, 334, 220,
       441, 581, 201, 493, 140, 206, 587, 353, 307, 360, 256, 325, 144,
       510, 619, 274, 469, 504, 377, 275, 501, 355, 629, 370, 439, 134,
       583, 599, 394, 533, 540, 128, 214, 634, 584, 574, 132, 447, 191,
       330, 314, 486, 293, 207, 463, 274], dtype=int32)

In [38]:
b

array([282, 641, 514, 603, 586, 573, 197, 390, 337, 583, 542, 416, 413,
       408, 450, 368, 440, 418, 398, 486, 609, 183, 524, 135, 380, 274,
       468, 364, 387, 342, 217, 404, 646, 514, 178, 237, 642, 357, 284,
       602, 212, 374, 302, 371, 536, 230, 618, 576, 187, 652, 130, 506,
       321, 559, 514, 537, 409, 346, 154, 494, 261, 565, 273, 392, 391,
       618, 319, 255, 302, 334, 292, 318, 615, 522, 494, 341, 373, 616,
       176, 164, 445, 311, 594, 462, 314, 282, 479, 438, 129, 581, 597,
       155, 150, 550, 368, 194, 352, 415, 508, 555, 431, 167, 334, 220,
       441, 581, 201, 493, 140, 206, 587, 353, 307, 360, 256, 325, 144,
       510, 619, 274, 469, 504, 377, 275, 501, 355, 629, 370, 439, 134,
       583, 599, 394, 533, 540, 128, 214, 634, 584, 574, 132, 447, 191,
       330, 314, 486, 293, 207, 463, 274], dtype=int32)

In [39]:
# elemanlarının toplamı
sum(b)

np.int32(59242)

In [41]:
toplam = np.sum(b)
print(toplam)

59242


In [43]:
print(b.sum())

59242


In [44]:
sum(b)

np.int32(59242)

In [46]:
# ortalama hesaplama :
ortalama = np.mean(b)
print(ortalama)

394.94666666666666


In [47]:
print(b.mean())

394.94666666666666


In [48]:
# standart  sapma
std_sapma = np.std(b)
print(std_sapma)

149.61126457887082


In [49]:
A = np.array([1,2,3])
B = np.array([10,45,78])
C = A + B
print(C)   

[11 47 81]


In [50]:
A = np.random.randint(0,1000,121)
A

array([ 50, 345,  41, 576,  26, 551, 666, 492,  43, 117, 734, 505, 400,
       905, 683, 752, 334, 890, 752, 899, 630, 698, 821, 452, 995, 958,
       199, 736, 424, 150, 992, 333, 721,  22, 424, 450, 257, 853, 486,
       832, 790, 365, 667, 670, 125, 956, 572, 513, 453, 730, 983, 812,
       136, 699, 510, 241, 941, 573, 371, 534, 410, 613, 934, 953, 296,
        51, 390,  40, 298, 747, 186, 146,  86, 211, 163, 308, 521, 879,
       244, 349, 131, 439, 150, 838, 231, 760, 921, 331, 423, 338, 766,
       530, 406, 819,  68, 702, 211, 900, 910, 217, 529, 490, 766, 188,
       354, 886, 983, 656,  59, 985, 542,  34, 638, 804, 459, 637, 740,
       650, 788, 649, 462], dtype=int32)

In [51]:
matris = A.reshape(11,11)
matris

array([[ 50, 345,  41, 576,  26, 551, 666, 492,  43, 117, 734],
       [505, 400, 905, 683, 752, 334, 890, 752, 899, 630, 698],
       [821, 452, 995, 958, 199, 736, 424, 150, 992, 333, 721],
       [ 22, 424, 450, 257, 853, 486, 832, 790, 365, 667, 670],
       [125, 956, 572, 513, 453, 730, 983, 812, 136, 699, 510],
       [241, 941, 573, 371, 534, 410, 613, 934, 953, 296,  51],
       [390,  40, 298, 747, 186, 146,  86, 211, 163, 308, 521],
       [879, 244, 349, 131, 439, 150, 838, 231, 760, 921, 331],
       [423, 338, 766, 530, 406, 819,  68, 702, 211, 900, 910],
       [217, 529, 490, 766, 188, 354, 886, 983, 656,  59, 985],
       [542,  34, 638, 804, 459, 637, 740, 650, 788, 649, 462]],
      dtype=int32)